# Generated by Django 5.1.4 on 2024-12-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.IntegerField()),
                ('encrypted_content', models.TextField()),
                ('decrypted_content', models.TextField(null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
